# --------- binds and stuff --------------
set -s escape-time 0

set -g prefix ^A
set -g base-index 1
set -g renumber-windows on
set -g default-terminal ${TERM}
setw -g mode-keys vi
set -g mouse on

bind + source-file ~/.tmux.conf

# ---------- theme stuff -----------------
set -g @plugin 'dracula/tmux'
set -g @dracula-plugins "ssh-session git time"
# left icon
# set -g @dracula-show-left-icon '🧉' 🚬
set -g @dracula-show-left-icon '𒉭'
# set -g @dracula-show-left-icon '🚬'
set -g @dracula-left-icon-fg "red dark-gray"
set -g @dracula-left-icon-bg "red dark-gray"
set -g @dracula-left-icon '𒉭'
# powerline
set -g @dracula-show-powerline false

set -g @dracula-show-flags true
# battery
set -g @dracula-show-battery-status true
# SSH
set -g @dracula-ssh-session-colors "white"
set -g @dracula-show-ssh-only-when-connected true
# time
set -g @dracula-military-time true
# weather
set -g @dracula-weather-colors "yellow"
# git
set -g @dracula-git-colors "green dark_gray"


# --------- non-theme plugins -------------
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'omerxx/tmux-session-manager'



run -b '~/.tmux/plugins/tpm/tpm'
